on:
    push:
      branches: [main]
    pull_request:
  
  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: 3.11.6
        - uses: snok/install-poetry@v1
          with:
            version: 1.7.1
            virtualenvs-create: true
            virtualenvs-in-project: true
        - run: poetry install --no-interaction
        - run: poetry run pytest