on:
    push:
        branches: [main]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.11.6"

        - name: Install Poetry
          uses: snok/install-poetry@v1
          with:
            version: 1.7.1
            virtualenvs-create: true
            virtualenvs-in-project: true

        - name: Install package and dependencies
          run: poetry install --no-interaction

        - name: Run tests
          run: poetry run pytest